server:
  port: 8080

spring:
  application:
    name: happy-pill
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false


--- # dev
spring.config.activate.on-profile: dev
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate.hibernate.format_sql: true



--- # prod
spring.config.activate.on-profile: prod
server.port: ${SERVER_PORT:80} # default http
spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_DATABASE_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create-drop  # validate