server:
  port: 8080

spring:
  application:
    name: happy-pill
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - openid
              - profile
              - email
          kakao:
            client-id: ${KAKAO_REST_API_KEY}
            #            client-secret:
            client-authentication-method: client_secret_post
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            scope:
              - openid
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            #            user-name-attribute: id
            issuer-uri: https://kauth.kakao.com

jwt:
  access-token-ttlSeconds: 6000
  refresh-token-ttlSeconds: 86400 # 60 * 60 * 24
  secret-key: ${JWT_SECRET_KEY:A1b2C3d4E5f6G7h8I9j0K1l2M3n4O5p6Q7r8S9t0U1v2W3x4Y5z6A7B8C9D0E1F2G3H4I5J6K7L8M9N0O1P2Q3R4S5T6U7V8W9X0Y1Z2a3b4c5d6e7f8g9h0i1j2k3l4m5n6o7p8q9r0s1t2u3v4w5x6y7z8A9B0C1D2E3F4G5H6}
  issuer: https://happypill-api.jiheon2234.dev

app:
  frontend:
    base-url: https://happypill.jiheon2234.dev
    login-path: /oauth-redirect


--- # dev
spring.config.activate.on-profile: dev
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate.hibernate.format_sql: true



--- # prod
spring.config.activate.on-profile: prod
server.port: ${SERVER_PORT:80} # default http
spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_DATABASE_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create-drop  # validate