services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: happy
      TZ: Asia/Seoul
    ports:
      - "5432:5432"
    command: >
      postgres -c log_statement=all -c logging_collector=off -c log_destination=stderr
    restart: unless-stopped

  redis:
    image: redis:8
    ports:
      - "6379:6379"
    restart: unless-stopped